#!/bin/bash
ping: 
    ansible -i inventory.ini all -m ping
ping-clients: 
    ansible -i inventory.ini nfs-client -m ping 
nfs-server: 
    ansible-playbook -i inventory.ini \
        playbooks/nfs-server.yaml 
nfs-main: 
    ansible-playbook -i inventory.ini \
        playbooks/nfs-main.yaml