server {
    listen 80;
    server_name reactjs-devop11.anajak-khmer.site; # Replace with your domain or IP

    location / {
        proxy_pass http://localhost:3000; # The address of your backend app
        
        # Recommended headers to pass client info to the backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
