services:
  backend-cont:
    image: spring:latest
    ports:
      - "8888:8080"
      - "9999:8181"
  reactjs-cont:
    image: reactjs:v1.0.0
    ports:
      - "8080:80"
    volumes:
      - ./reactjs-conf:/etc/nginx/nginx.conf:rw

network: 
volumes: 
