server {
    listen 80;
    server_name reactjs.istad.dev;
    location / {
        proxy_pass http://localhost:3000;
        include proxy_params; # Includes recommended header forwarding
         # Forward the upgrade headers
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Optional: Forward client information and adjust timeouts
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400s; # Set a high timeout for long-lived connections
        proxy_buffering off; # Disable buffering for real-time communication
    }
}

