apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app.kubernetes.io/name: nginx-pod
spec:
  containers:
  - name: nginx-cont 
    image: nginx:latest
    ports:
      - containerPort: 80

