apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-image-pvc
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  # use the storage class that provided by provisioner we installed earlier 
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany