apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dpl
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      # select specific worker node to run 
      nodeSelector: 
        kubernetes.io/hostname: worker02
      containers:
      - name: spring-app
        image: 69966/springgradleimg:1.1.1
        ports:
        - containerPort: 8080
        volumeMounts: 
          - name: image-vol 
            mountPath: /app/src/main/resources/images
      volumes: 
        - name: image-vol
          persistentVolumeClaim:
            claimName: nfs-storage-pvc
